COVID Relational dataset
jamadaha/P6 pull request #188
Opened 2022-04-12 11:16 UTC by kris701

Added a relational dataset over Covid data. Adds to the issue #98.

2022-04-13 11:26 UTC, HGinnerup requested changes
System.IndexOutOfRangeException: 'Bucket end value cannot be lower than start value!'

During run using covid data

2022-04-13 13:10 UTC, kris701 commented
> System.IndexOutOfRangeException: 'Bucket end value cannot be lower than start value!'
> 
> During run using covid data

Do purge your Histogram cache before attempting to run this.

2022-04-18 06:27 UTC, jamadaha approved these changes

2022-04-18 08:09 UTC, HGinnerup approved these changes

2022-04-18 08:09 UTC, merged