Initial experiment 3
jamadaha/P6 pull request #192
Opened 2022-04-13 07:35 UTC by HGinnerup

2022-04-13 07:36 UTC, jamadaha approved these changes

2022-04-13 07:39 UTC, jamadaha requested changes
Crashes on run

2022-04-13 07:45 UTC, kris701 requested changes

2022-04-13 07:45 UTC, kris701 commented on Jantimizer/Histograms/Managers/MinDepthHistogramManager.cs
> +            var retVal = HistogramCacher.Instance.GetValueOrNull(new string[] { tableName, attributeName, hash, Depth.ToString() });
Missing `typeof(HistogramMinDepth).Name` as well (Look at the `CacheHistogram()` function to see what strings are used in the hash)

2022-04-13 07:47 UTC, jamadaha requested changes

2022-04-13 07:47 UTC, jamadaha commented on Jantimizer/ExperimentSuite/experiments.json
> +      "ExperimentName": "Experiment One_min",
Is this not experiment 3?

2022-04-18 10:44 UTC, kris701 submitted a review, later dismissed

2022-04-18 10:44 UTC, kris701 commented on Jantimizer/ExperimentSuite/experiments.json
> +            "COVID_Funding_Setup"
I guess you just stole the issue i was working on :'(

2022-04-18 10:44 UTC, kris701 commented on Jantimizer/ExperimentSuite/experiments.json
> +            "COVID_Funding_Setup"
Also i still think its a better idea to wait with merging all these, until the optimiser can actually *work* with them.

2022-04-18 11:08 UTC, kris701 requested changes

2022-04-18 11:08 UTC, kris701 commented on Jantimizer/ExperimentSuite/experiments.json
> +        "BucketSize": 10
Please do set all the bucketsizes to be like 256 instead

2022-04-18 11:12 UTC, kris701 approved these changes

2022-04-18 11:18 UTC, jamadaha approved these changes
It runs

2022-04-18 11:41 UTC, merged