Query Parser
jamadaha/P6 pull request #29
Opened 2022-03-09 10:01 UTC by kris701

Made a class library to parse queries. Currently specificly Join queries, however it is made to be extendable with further parsers.

2022-03-09 11:40 UTC, jamadaha submitted a review, later dismissed
Seems fine, although I haven't the faintest idea of what's going on

2022-03-09 13:01 UTC, HGinnerup requested changes

2022-03-10 07:11 UTC, jamadaha approved these changes

2022-03-10 07:16 UTC, HGinnerup approved these changes

2022-03-10 07:16 UTC, merged