Add and and or
jamadaha/P6 pull request #74
Opened 2022-03-17 18:44 UTC by jamadaha

- Closes #71 
- Closes #50

2022-03-17 18:48 UTC, jamadaha commented on Jantimizer/QueryParser/QueryParsers/PostgresParser.cs
>                      id++,
I don't know what this does. So have removed it for now

2022-03-18 08:09 UTC, kris701 requested changes

2022-03-18 08:09 UTC, kris701 commented on Jantimizer/QueryParser/QueryParsers/PostgresParser.cs
> +        public static ParserResult AnalyseExplanationText(string explanationText)
Lots of static methods here? why? its an instantiated class anyway, so you would have to make a `new PostgresParser(...)` anyway, before you could even call this function.
Same goes for the rest of the static functions in this class.

2022-03-18 12:06 UTC, kris701 approved these changes
Seems to work.

2022-03-19 17:47 UTC, kris701 approved these changes

2022-03-19 17:47 UTC, merged